name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pr-labeler.glitch.me

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          token: '${{ secrets.GH_PAT }}'
          ref: 'main'

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: '${{ secrets.GH_PAT }}'

      - name: Deploy project to Glitch
        run: |
          npx glitcheroo deploy
        env:
          GLITCHEROO_GIT_URL: ${{ secrets.GLITCHEROO_GIT_URL }}
